# Generated by Django 5.2.14 on 2026-05-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_card_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='books', to='api_v1.author')),
                ('categories', models.ManyToManyField(related_name='books', to='api_v1.category')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api_v1.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookCardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Выдана', 'Выдана'), ('Продлена', 'Продлена'), ('Возвращена', 'Возвращена'), ('Просрочена', 'Просрочена')], default='Выдана', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.book')),
                ('book_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_v1.bookcard')),
            ],
        ),
        migrations.AddField(
            model_name='bookcard',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_card', to='api_v1.reader'),
        ),
    ]
